### ISSUE TITLE
Paralellize package tests

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#119]
Right now, tee have an action that runs each test suite one right after the other. However, the test suites are completely independent from each other and so to allow for maximum dev cycles, we should run them in parallel.

**Comment by cowboyd** [comment]
We'd like to

1. prepack all packages first before running the tests (with the exception of the website)
2. upload the `/dist` directories as GitHub action artifacts
3. each test job downloads the `/dist` directories to get the compiled npm packages, and runs its tests.
4. runs tests

**Comment by minkimcello** [comment]
So I gave it some thought and this is what I have in mind:

```
name: Test Workflow

on: pull request

jobs:
  upload:
    name: Prepack and Upload 
    steps:
    - uses: checkout
    - uses

```
